/**
 * The screenshots in the README, taken from the app itself.
 *
 * Run with: npm run build && npm run shots
 *
 * Boots the built app the way a user does — its own main process, its own
 * database, its own media — and drives it over the Chrome DevTools Protocol,
 * so `docs/screenshots/` holds the app running rather than a mock of it. A
 * README that shows a mock ages into a lie the first time a screen changes;
 * this one is regenerated by rerunning the script.
 *
 * It captures the web contents, not the OS window, so the frame around the
 * shots is the app's own chrome and nothing of whoever ran it.
 *
 * The screens it visits are the ones the README's table describes, in the same
 * order, and it fails loudly when a click finds nothing — a screenshot of the
 * wrong screen is worse than no screenshot, because nobody checks.
 */
import { spawn } from 'node:child_process'
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { platform } from 'node:process'

const PORT = 9222
const OUT = resolve('docs/screenshots')
const ELECTRON = resolve(
  'node_modules/electron/dist',
  platform === 'win32' ? 'electron.exe' : platform === 'darwin' ? 'Electron.app/Contents/MacOS/Electron' : 'electron'
)

/** The song the tour is built around: it has a tab, audio, stems, a chart and videos. */
const SONG = 'Like a Stone'

const wait = (ms) => new Promise((r) => setTimeout(r, ms))

/* -------------------------------------------------------------------- CDP */

let ws
let nextId = 1
const pending = new Map()

function send(method, params = {}) {
  const id = nextId++
  ws.send(JSON.stringify({ id, method, params }))
  return new Promise((ok, fail) => {
    pending.set(id, { ok, fail })
    setTimeout(() => {
      if (pending.delete(id)) fail(new Error(`${method} não respondeu`))
    }, 60000)
  })
}

/** Evaluate an expression in the page and get the value back. */
async function evaluate(expression) {
  const res = await send('Runtime.evaluate', {
    expression,
    returnByValue: true,
    awaitPromise: true
  })
  if (res.exceptionDetails) {
    throw new Error(res.exceptionDetails.exception?.description ?? 'erro no renderer')
  }
  return res.result.value
}

async function connect() {
  const deadline = Date.now() + 30000
  for (;;) {
    try {
      const list = await fetch(`http://127.0.0.1:${PORT}/json/list`).then((r) => r.json())
      const page = list.find((t) => t.type === 'page' && t.url.startsWith('app://'))
      if (page) {
        ws = new WebSocket(page.webSocketDebuggerUrl)
        await new Promise((ok, fail) => {
          ws.onopen = ok
          ws.onerror = () => fail(new Error('a conexão de depuração foi recusada'))
        })
        ws.onmessage = (ev) => {
          const msg = JSON.parse(ev.data)
          const slot = pending.get(msg.id)
          if (!slot) return
          pending.delete(msg.id)
          if (msg.error) slot.fail(new Error(msg.error.message))
          else slot.ok(msg.result)
        }
        return
      }
    } catch {
      // the app is still starting and the endpoint is not listening yet
    }
    if (Date.now() > deadline) throw new Error('o app não abriu a porta de depuração')
    await wait(400)
  }
}

/* ---------------------------------------------------------------- driving */

/**
 * Click the innermost visible thing whose text contains `text`.
 *
 * `[role="button"]` matters as much as `button`: the setlist rows are divs that
 * carry the role, and the tour opens a song through one. That is also why the
 * innermost match is the one to take — an expanded row *contains* the buttons
 * it offers, so its own text contains theirs, and clicking the outer one just
 * folds the row shut again.
 */
async function click(text) {
  const hit = await evaluate(`(() => {
    const want = ${JSON.stringify(text)}.toLowerCase()
    const matches = [...document.querySelectorAll('button, [role="button"], a')].filter((x) => {
      if (x.disabled || !x.offsetParent) return false
      return ((x.innerText || x.getAttribute('aria-label') || '').trim().toLowerCase()).includes(want)
    })
    const el = matches.find((x) => !matches.some((y) => y !== x && x.contains(y)))
    if (!el) return false
    el.scrollIntoView({ block: 'center' })
    el.click()
    return true
  })()`)
  if (!hit) throw new Error(`não achei nada clicável com "${text}"`)
  await wait(500)
}

/** Like `click`, but a miss is an answer rather than a failure. */
async function clickIfPresent(text) {
  try {
    await click(text)
    return true
  } catch {
    return false
  }
}

/** Click the button whose label starts with `prefix` — for "Todas (33)". */
async function clickPrefix(prefix) {
  const hit = await evaluate(`(() => {
    const want = ${JSON.stringify(prefix)}.toLowerCase()
    const el = [...document.querySelectorAll('button')].find(
      (x) => x.offsetParent && (x.innerText || '').trim().toLowerCase().startsWith(want)
    )
    if (!el) return false
    el.click()
    return true
  })()`)
  if (!hit) throw new Error(`não achei um botão começando com "${prefix}"`)
  await wait(500)
}

/** Click one of the icon buttons, which are addressed by their tooltip. */
async function clickTitle(title) {
  const hit = await evaluate(`(() => {
    const el = document.querySelector(${JSON.stringify(`button[title="${title}"], button[aria-label="${title}"]`)})
    if (!el) return false
    el.click()
    return true
  })()`)
  if (!hit) throw new Error(`não achei o botão "${title}"`)
  await wait(500)
}

async function waitFor(expression, timeoutMs, label) {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    const value = await evaluate(`(() => { try { return ${expression} } catch { return false } })()`)
    if (value) return value
    if (Date.now() > deadline) throw new Error(`tempo esgotado esperando ${label}`)
    await wait(300)
  }
}

/** Wait until the screen is showing this text. */
const waitForText = (text, timeoutMs = 15000) =>
  waitFor(`document.body.innerText.includes(${JSON.stringify(text)})`, timeoutMs, `"${text}" na tela`)

/**
 * Scroll the pane that actually scrolls, by `px`.
 *
 * Every screen keeps its own scroll container, so there is no one element to
 * name. The tallest overflowing one is the content, which is what a shot of a
 * long chart or a video list needs moved off its header.
 */
async function scrollBy(px) {
  await evaluate(`(() => {
    const panes = [...document.querySelectorAll('*')].filter(
      (el) => el.scrollHeight > el.clientHeight + 40 && el.clientHeight > 200
    )
    const pane = panes.sort((a, b) => b.clientHeight - a.clientHeight)[0]
    if (pane) pane.scrollTop += ${px}
    return true
  })()`)
  await wait(600)
}

const shots = []
async function shoot(name, note) {
  // let the transition finish and any lazy image arrive before the shutter
  await wait(900)
  const { data } = await send('Page.captureScreenshot', { format: 'png' })
  const bytes = Buffer.from(data, 'base64')
  writeFileSync(join(OUT, `${name}.png`), bytes)
  shots.push(name)
  console.log(`  ${name}.png  ${String(Math.round(bytes.length / 1024)).padStart(4)} kB   ${note}`)
}

/* ------------------------------------------------------------------- main */

if (!existsSync(resolve('out/renderer/index.html'))) {
  console.error('rode npm run build antes — não há bundle em out/renderer')
  process.exit(1)
}
mkdirSync(OUT, { recursive: true })

/** The app's environment, minus the flag that would boot Electron as plain node. */
function appEnv() {
  const env = { ...process.env }
  // the test scripts export it; here it would start node instead of the app
  delete env.ELECTRON_RUN_AS_NODE
  return env
}

const child = spawn(ELECTRON, ['.', `--remote-debugging-port=${PORT}`], {
  env: appEnv(),
  stdio: ['ignore', 'ignore', 'pipe']
})
child.stderr.on('data', (d) => {
  const line = String(d).trim()
  // the DevTools banner is the handshake working, not a problem
  if (line && !line.includes('DevTools listening')) console.error(`[app] ${line}`)
})

const done = (code) => {
  try {
    child.kill()
  } catch {
    // it already exited
  }
  process.exit(code)
}

try {
  await connect()
  await waitFor('document.querySelectorAll("button").length > 3', 30000, 'a interface montar')
  console.log('app aberto\n')

  /*
   * The first-run banner talks about FFmpeg and missing keys. It is honest and
   * it belongs in the app, but it is not what the README is showing, and it
   * covers the top of the first screen.
   */
  await evaluate(`(() => {
    const b = [...document.querySelectorAll('button')].find((x) =>
      /dispensar|entendi|agora não|fechar/i.test(x.innerText || '')
    )
    if (b) b.click()
    return true
  })()`)

  await shoot('01-setlist', 'setlist, prontidão e ordem do show')

  /*
   * The tour needs the song on screen, and the setlist that is active when the
   * script starts is whatever the user left active. Fall back to the whole
   * library rather than fail: the row is the same either way.
   */
  if (!(await clickIfPresent(SONG))) {
    await clickPrefix('Todas (')
    await wait(700)
    await click(SONG)
  }
  await waitForText('Abrir música')
  await shoot('02-setlist-musica', 'uma música aberta na lista')

  await click('Abrir música')
  await waitForText('Visão geral')
  await shoot('03-musica', 'a música e o progresso por trecho')

  await click('Tablatura')
  await waitFor('document.querySelectorAll("canvas, svg").length > 4', 90000, 'a partitura renderizar')
  // alphaTab lays the score out in a worker; the first page is not the last word
  await wait(6000)
  await shoot('04-tablatura', 'Guitar Pro com player, loop A/B e metrônomo')

  await click('Stems')
  await waitFor('document.querySelectorAll("canvas").length > 0', 60000, 'as faixas carregarem')
  await wait(5000)
  await shoot('05-stems', 'faixas separadas, velocidade e loop na forma de onda')

  await click('Cifra')
  await wait(2500)
  // past the detected-chord grid, onto the written cifra and the lyric beside it
  await scrollBy(760)
  await shoot('06-cifra', 'cifra e letra sincronizada')

  await click('Vídeos')
  await wait(3500)
  // past the embedded player, which is a black rectangle until someone presses play
  await scrollBy(1020)
  await shoot('07-videos', 'aulas, backing tracks e playthroughs, já classificados')

  await click('Timbre')
  await wait(3000)
  await shoot('08-timbre', 'patches de timbre por trecho')

  /*
   * The lab is reached through the song rather than from the bottom bar: with
   * no song chosen it is an empty picker, and with one it shows that song's
   * analyses and their history.
   */
  await click('Laboratório')
  await wait(3000)
  await shoot('09-laboratorio', 'separação de stems e análise de áudio')

  await clickTitle('Progresso')
  await wait(3000)
  await shoot('10-progresso', 'fila de hoje, constância e curva de BPM')

  await clickTitle('Afinador')
  await wait(3000)
  await shoot('11-afinador', 'afinador com o preset da música')

  await clickTitle('Modo Palco')
  await wait(3000)
  // past the ChordPro header, onto the lyrics and chords the mode is for
  await scrollBy(430)
  await shoot('12-palco', 'modo palco')

  console.log(`\n${shots.length} imagens em docs/screenshots/`)
  done(0)
} catch (err) {
  console.error(`\nFALHA: ${err.message}`)
  try {
    console.error(`\ntela:\n${(await evaluate('document.body.innerText')).slice(0, 1200)}`)
  } catch {
    console.error('tela: o renderer não respondeu')
  }
  done(1)
}
